apiVersion: v1
kind: Service
metadata:
  name: {{ include "snoutguard.fullname" . }}-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snoutguard.fullname" . }}-dashboard
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dashboard.port }}
      targetPort: {{ .Values.dashboard.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: dashboard
